### ISSUE TITLE
Qconfig does not search for localized strings

### ISSUE THREAD

**Issue by amenk** [tim-reynolds/magento-qconfig#10]
- use german language pack
- search for "Bundesland" ( = State)
- nothing found

**Comment by tim-reynolds** [comment]
On the road. Will try to fix tonight. Great find!

**Comment by amenk** [comment]
Tomorrow morning will be also okay.

Just kidding - take your time :-)

**Comment by amenk** [comment]
What do you think about a config option "Include Original (English) Texts into Search". It think it should be false by default but could be useful for power users who know the english strings but work occasionally with the localized interface.

**Comment by tim-reynolds** [comment]
Well I saw the German admin translation was released/updated this week. I think I can handle translating is. It runs out I don't have Internet where I am currently so won't be able to fix until tomorrow or Monday. 

Since I'm caching the sections of the config I will just need to run them through the locale translation and add the locale to the cache tag name. 

Do you know if there are many other admin translations? (Sadly only read English and some Latin )

**Comment by amenk** [comment]
I do not know if there are other admin translations - but some custom models also bring translations in their language.

Does the actual language matter?

**Comment by tim-reynolds** [comment]
Just FYI, haven't forgotten about this. Been super busy with new company. Hoping to have it done this week. 

Tim

**Comment by amenk** [comment]
okay :-) good luck with your new company!

**Comment by amenk** [comment]
working on it...

**Comment by amenk** [comment]
Implemented.

What is currently not supported are german umlauts ('Ä', 'ä') because those are not in the translation table for lowercasing the stuff ... we should add this processing somewhere else.

Tested with https://github.com/riconeitzel/German_LocalePack_de_DE

**Comment by amenk** [comment]
Hm I think we could close that?
