### ISSUE TITLE
Search for email -> shows match in General Desgin, but where is it?

### ISSUE THREAD

**Issue by amenk** [tim-reynolds/magento-qconfig#5]
![Screenshot](https://raw.github.com/amenk/misc/master/qconfig-match-not-found.png)

**Comment by tim-reynolds** [comment]
Well, this is one of those unfortunate things. There are config elements that aren't represented with an entry in system.xml. I hadn't encountered one on a common word. Email is a pretty common word. I will have to look at what is matching it. 

Interesting note, sometimes you will search for something, it will show it being in a group, but you can't see the actual field. That is because the field is hidden (check a box and it will show up sort of thing). 

Thinking about it, I wonder if I'm going to have to do the more manual processing of XML that I hoped to avoid (as mentioned in the other issue)

**Comment by tim-reynolds** [comment]
Ok, I looked into this. Should have paid attention to the image. It is matching the label "Transactional Emails" 

What I need to change is, if you match a group, mark the group and show that it is matching somehow. 

Or, I could try not matching the groups, but I don't like that. Hmm... I have some ideas then.

**Comment by tim-reynolds** [comment]
Better still, I did support this /facepalm, however there was a bug. So, fixed the bug. Going to add something more though...

**Comment by tim-reynolds** [comment]
Fixed 
![Image](http://i.imgur.com/XHIaH.png)
